language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=allegro
    - LISP=abcl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/quri ~/lisp/quri
  - git clone https://github.com/fukamachi/proc-parse ~/lisp/proc-parse

script:
  - cl -l prove
       -e '(or (prove:run :cl-cookie-test) (uiop:quit -1))'
